package tanghuibo.github.io.activitistudy.dao;

import org.apache.ibatis.annotations.Mapper;
import tanghuibo.github.io.activitistudy.entity.BasicUserDO;

@Mapper
public interface BasicUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_user
     *
     * @mbg.generated Wed Mar 18 01:26:53 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_user
     *
     * @mbg.generated Wed Mar 18 01:26:53 CST 2020
     */
    int insert(BasicUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_user
     *
     * @mbg.generated Wed Mar 18 01:26:53 CST 2020
     */
    int insertSelective(BasicUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_user
     *
     * @mbg.generated Wed Mar 18 01:26:53 CST 2020
     */
    BasicUserDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_user
     *
     * @mbg.generated Wed Mar 18 01:26:53 CST 2020
     */
    int updateByPrimaryKeySelective(BasicUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table basic_user
     *
     * @mbg.generated Wed Mar 18 01:26:53 CST 2020
     */
    int updateByPrimaryKey(BasicUserDO record);
}